<?php

/**
 * @file
 * Custom module for Career quiz.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_type_build().
 */
function ccext_entity_type_build(array &$entity_types) {
  if (isset($entity_types['entity_comparison'])) {
    $entity_types['entity_comparison']->setClass('Drupal\ccext\Entity\CcextEntityComparison');
  }
}

/**
 * Implements hook_theme().
 */
function ccext_theme($existing, $type, $theme, $path) {
  return [
    'career_profile_comparison' => [
      'variables' => [
        'id' => NULL,
        'rows' => NULL,
        '#empty' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_query_alter().
 */
function ccext_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'career_matches' && 'block_1' == $view->current_display) {
    $title = NULL;
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface) {
      // You can get nid and anything else you need from the node object.
      $nid = $node->id();
      $session = \Drupal::request()->getSession();
      $save_quiz = $session->get('SavedQuiz');
      $quiz_result = $save_quiz['save_quiz_' . $node->bundle() . "_$nid"];
      if (!empty($save_quiz) && isset($quiz_result) && !empty($quiz_result->result)) {
        foreach ($quiz_result->result as $key => $value) {
          if (strlen((string) $key) == 2) {
            $key = '00' . $key;
          }
          elseif (strlen((string) $key) == 3) {
            $key = '0' . $key;
          }
          $title[] = $key;
        }
      }
    }
    $query->addWhere('0', 'node_field_data.title', $title, 'IN');
  }
}

/**
 * Implements hook_mail().
 */
function ccext_mail($key, &$message, $params) {
  switch ($key) {
    case 'email':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['headers'] = [
        'MIME-Version' => '1.0',
        'Content-Type' => 'text/html; charset=UTF-8; format=flowed; delsp=yes',
        'Content-Transfer-Encoding' => '8Bit',
        'X-Mailer' => 'Drupal',
      ];
      $message['params']['attachments'][] = $params['attachments'];
      break;
  }
}
