<?php

use Drupal\webform\Entity\WebformSubmission;

function quizzesList() {
  $forms = \Drupal::entityTypeManager()->getStorage('webform')->loadMultiple();
  return array_reduce($forms, function($quizzes, $form) {
    if (str_ends_with($form->id(), '_quiz')) {
      $quizzes[$form->id()] = $form->get('title');
    }
    return $quizzes;
  }, []);
}

function getUserSubmission($webform_id) {

  $current_user = \Drupal::currentUser();
  $query = \Drupal::entityQuery('webform_submission')
  ->condition('uid', $current_user->id())
  ->condition('webform_id', $webform_id)
  ->range(0, 1)
  ->accessCheck(false);

  $results = $query->execute();
  if ($results) {
    $sid = array_shift($results);
    $webform_submission = WebformSubmission::load($sid);
  }

  return isset($webform_submission) ? $webform_submission : false;
}
